version: '3.9'

networks:
  default:
    name: desafiodock

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: "no"
    environment:
      SA_PASSWORD: "Password1?"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'

  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "sqlserver"
    restart: "no"
    restart: "always"
