version: '3.9'

networks:
  default:
    name: desafiodock

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: "no"
    environment:
      SA_PASSWORD: "Password1?"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'

  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "sqlserver"
    restart: "no"
#    volumes:
#      - ${postgresData}:/var/lib/postgresql/data
#      - ${createTables}:/docker-entrypoint-initdb.d/create_tables.sql
#      - ${fillTables}:/docker-entrypoint-initdb.d/fill_tables.sql
